language: node_js

sudo: required
services:
  - docker

before_script:
  - docker build --tag tbase -f Dockerfile.base .
  - docker build --tag tbuild -f Dockerfile.build .
  - # Check that repository is in sane state
  - docker run -e LOCAL_USER_ID=`id -u $USER` -v "$(pwd)"/augur-trampoline:/src tbuild yarn install --offline
  - git status && git diff && test -z "$(git status --porcelain)"
  - docker run -e LOCAL_USER_ID=`id -u $USER` -v "$(pwd)"/augur-trampoline:/src tbuild npm-run flow version

script:
  - docker run -v "$(pwd)"/augur-trampoline:/src tbuild yarn lint
  - docker run -v "$(pwd)"/augur-trampoline:/src tbuild yarn flow
  - docker run -e LOCAL_USER_ID=`id -u $USER` -v "$(pwd)"/augur-trampoline:/src -e CI=1 tbuild yarn test --coverage
  - docker run -e LOCAL_USER_ID=`id -u $USER` -v "$(pwd)"/augur-trampoline:/src tbuild yarn build
  - docker build --tag tdev -f Dockerfile.dev .
  - docker build --tag ipfs_show -f Dockerfile.ipfs_show .

after_script:
  - docker run --rm -v "$(pwd)/build":/build ipfs_show
  - docker images
  - git status
  - git status && git diff
