#!/bin/bash

set -euo pipefail

REPO="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

LABEL=augur-trampoline-nuclide-server-container

function show_container_id() {
	docker ps -f "label=$LABEL" -q | grep -E .
}

if ! show_container_id > /dev/null; then
	docker run \
		-d \
		--rm \
		-e LOCAL_USER_ID=`id -u $USER` \
		-v $REPO:/src \
		-v /tmp:/tmp \
		-l $LABEL \
		-p 9090:9090 -p 9091:9091 -p 9092:9092 -p 9093:9093 \
		dev \
		bash -c 'sleep 864000' \
		> /dev/null;
	# sleep-based synchronization lol
	# container creates a user early on, and we want to run exec
	# only after the user has been created
	sleep 5;
fi

docker exec \
	-it \
	-u user \
	$(show_container_id) \
	nuclide-start-server \
	"$@"
