// flow-typed signature: 3447fa79b7bce2cb8b78966b891045e3
// flow-typed version: <<STUB>>/augur-core_vAugurProject/augur-core.git#0df03124b5181bed8298832eeda24308be911d08/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'augur-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'augur-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'augur-core/source/tools/generateCoverageReport' {
  declare module.exports: any;
}

declare module 'augur-core/typings/bn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'augur-core/source/tools/generateCoverageReport.js' {
  declare module.exports: $Exports<'augur-core/source/tools/generateCoverageReport'>;
}
declare module 'augur-core/typings/bn.js' {
  declare module.exports: $Exports<'augur-core/typings/bn'>;
}
