// flow-typed signature: 15bf52dd101fd0c075066a030686d913
// flow-typed version: <<STUB>>/shallow-compare_v^1.2.2/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shallow-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shallow-compare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shallow-compare/es/index' {
  declare module.exports: any;
}

declare module 'shallow-compare/lib/index' {
  declare module.exports: any;
}

declare module 'shallow-compare/umd/shallow-compare' {
  declare module.exports: any;
}

declare module 'shallow-compare/umd/shallow-compare.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shallow-compare/es/index.js' {
  declare module.exports: $Exports<'shallow-compare/es/index'>;
}
declare module 'shallow-compare/lib/index.js' {
  declare module.exports: $Exports<'shallow-compare/lib/index'>;
}
declare module 'shallow-compare/umd/shallow-compare.js' {
  declare module.exports: $Exports<'shallow-compare/umd/shallow-compare'>;
}
declare module 'shallow-compare/umd/shallow-compare.min.js' {
  declare module.exports: $Exports<'shallow-compare/umd/shallow-compare.min'>;
}
